const INCREMENT = 'INCREMENT'
const DECREMENT = 'DECREMENT'
const INPUT_TEXT = 'INPUT_TEXT'
const COMMENT_CREATE = 'COMMENT_CREATE'
const COMMENT_UPDATE = 'COMMENT_UPDATE'
const COMMENT_DELETE = 'COMMENT_DELETE'

const COMMENTS_LOAD = 'COMMENTS_LOAD'
const LOADER_DISPLAY_ON = 'LOADER_DISPLAY_ON'
const LOADER_DISPLAY_OFF = 'LOADER_DISPLAY_OFF'

const ERROR_DISPLAY_ON = 'ERROR_DISPLAY_ON'
const ERROR_DISPLAY_OFF = 'ERROR_DISPLAY_OFF'

export {INCREMENT, DECREMENT, INPUT_TEXT, COMMENT_CREATE, COMMENT_UPDATE, COMMENT_DELETE, COMMENTS_LOAD, LOADER_DISPLAY_ON, LOADER_DISPLAY_OFF, ERROR_DISPLAY_ON, ERROR_DISPLAY_OFF}